volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: nelo05/kittygram_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media:/app/media
      - static:/app/static

  frontend:
    env_file: .env
    image: nelo05/kittygram_frontend
    depends_on:
      - backend
    command: cp -r /app/build/. /static
    volumes:
      - static:/static
  gateway:
    image: nelo05/kittygram_gateway
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
